"""Modelos Pydantic v2 del dominio.

Punto de importación único: ``from packages.core_domain.esquemas import FactSet, Recibo, ...``
(los submódulos siguen siendo importables por separado si se prefiere).
"""

from packages.core_domain.esquemas.auditoria import (
    HASH_GENESIS,
    EventoAuditoria,
    json_canonico,
)
from packages.core_domain.esquemas.evaluacion import CasoGolden, GroundTruthCausaDelta
from packages.core_domain.esquemas.factset import (
    CAMPOS_EXCLUIDOS_DEL_HASH,
    NAMESPACE_FACTSET,
    TOLERANCIA_RESIDUAL_CENT,
    CausaAgregada,
    FactSet,
    Invariante,
    LineaDelta,
    token_entero,
    token_fecha,
    token_monto,
    token_periodo,
    token_porcentaje,
)
from packages.core_domain.esquemas.movimiento import (
    MODELOS_DETALLE,
    CuotaFinanciamiento,
    DetalleAltaEquipoFinanciado,
    DetalleAltaPaquete,
    DetalleCambioPlan,
    DetalleFinDescuento,
    DetalleNota,
    DetalleReconexion,
    DetalleSuspension,
    MovementEvent,
    PlanFinanciamiento,
)
from packages.core_domain.esquemas.recibo import (
    MESES_ES,
    ConceptoCatalogo,
    LineaRecibo,
    Periodo,
    Recibo,
    Tramo,
    etiqueta_rango_fechas,
)
from packages.core_domain.esquemas.respuesta import (
    Accion,
    Asercion,
    BarraPuente,
    Bloque,
    BloqueAviso,
    BloqueKV,
    BloquePuente,
    BloqueTabla,
    BloqueTexto,
    Cita,
    Derivacion,
    Gobernanza,
    ItemEvidencia,
    ItemKV,
    PeticionDerivacion,
    PeticionExplicacion,
    RespuestaCanalAgnostica,
    RespuestaError,
)

__all__ = [
    "CAMPOS_EXCLUIDOS_DEL_HASH",
    "HASH_GENESIS",
    "MESES_ES",
    "MODELOS_DETALLE",
    "NAMESPACE_FACTSET",
    "TOLERANCIA_RESIDUAL_CENT",
    "Accion",
    "Asercion",
    "BarraPuente",
    "Bloque",
    "BloqueAviso",
    "BloqueKV",
    "BloquePuente",
    "BloqueTabla",
    "BloqueTexto",
    "CasoGolden",
    "CausaAgregada",
    "Cita",
    "ConceptoCatalogo",
    "CuotaFinanciamiento",
    "Derivacion",
    "DetalleAltaEquipoFinanciado",
    "DetalleAltaPaquete",
    "DetalleCambioPlan",
    "DetalleFinDescuento",
    "DetalleNota",
    "DetalleReconexion",
    "DetalleSuspension",
    "EventoAuditoria",
    "FactSet",
    "Gobernanza",
    "GroundTruthCausaDelta",
    "Invariante",
    "ItemEvidencia",
    "ItemKV",
    "LineaDelta",
    "LineaRecibo",
    "MovementEvent",
    "Periodo",
    "PeticionDerivacion",
    "PeticionExplicacion",
    "PlanFinanciamiento",
    "Recibo",
    "RespuestaCanalAgnostica",
    "RespuestaError",
    "Tramo",
    "etiqueta_rango_fechas",
    "json_canonico",
    "token_entero",
    "token_fecha",
    "token_monto",
    "token_periodo",
    "token_porcentaje",
]
